### ISSUE TITLE
[FEATURE] - Create Header and Hero Section for Tcet Linux Website

### ISSUE THREAD

**Issue by riyavishwa981** [tcet-opensource/tcet-linux-website#2]
- Make it responsive
- Make correct use of fonts and colors refer the [design](https://www.figma.com/file/FkvsKAzBklfluSlz6iuT3o/TCET-%E2%80%A2-Linux?node-id=0-1&t=PmhQwZFw52UrVSw7-0) for the same
- Make branch name as issue_no-header-and-hero-section

**Comment by JayeshVP24** [comment]
solved in #15
