### ISSUE TITLE
[FEATURE] - Create Downloads Section

### ISSUE THREAD

**Issue by riyavishwa981** [tcet-opensource/tcet-linux-website#3]
- Make it responsive
- Make correct use of fonts and colors refer the [design](https://www.figma.com/file/FkvsKAzBklfluSlz6iuT3o/TCET-%E2%80%A2-Linux?node-id=0-1&t=PmhQwZFw52UrVSw7-0) for the same
- Make branch name as issue_no-download-section (issue number is the number which is mentioned with this issue in your case it is 3 so your branch name will be 3-download-section)

**Comment by JayeshVP24** [comment]
resolved in #13
