### ISSUE TITLE
[FEATURE] - Create Verify Downloads Section for Tcet Linux Website

### ISSUE THREAD

**Issue by riyavishwa981** [tcet-opensource/tcet-linux-website#5]
- Make it responsive
- Make correct use of fonts and colors refer the [design](https://www.figma.com/file/FkvsKAzBklfluSlz6iuT3o/TCET-%E2%80%A2-Linux?node-id=0-1&t=PmhQwZFw52UrVSw7-0) for the same
- Make branch name as issue_no-verify-downloads-section (issue number is the number which is mentioned with this issue in your case it is 5 so your branch name will be 5-verify-downloads-section)

**Comment by JayeshVP24** [comment]
#17
