### ISSUE TITLE
[FEATURE] - Create Footer for Tcet Linux Website

### ISSUE THREAD

**Issue by riyavishwa981** [tcet-opensource/tcet-linux-website#6]
- Make it responsive
- Make correct use of fonts and colors refer the [design](https://www.figma.com/file/FkvsKAzBklfluSlz6iuT3o/TCET-%E2%80%A2-Linux?node-id=0-1&t=PmhQwZFw52UrVSw7-0) for the same
- Make branch name as issue_no-footer-section (issue number is the number which is mentioned with this issue in your case it is 6 so your branch name will be 6-footer-section)

**Comment by JayeshVP24** [comment]
done and dusted #12
