### ISSUE TITLE
[DEPLOY] Deploy staging in netlify

### ISSUE THREAD

**Issue by JayeshVP24** [tcet-opensource/tcet-linux-website#8]
# Deployment of Staging
Static deployment of tcet-linux  staging branch to netlify
all PRs to staging should make a preview. Do add that feature!

**Comment by VedantPol** [comment]
Please add the test-Linux-website Repo to Netlify . Currently, the repository is not configured for it.

**Comment by VedantPol** [comment]
hey @JayeshVP24 ,
Published the main branch to Netlify.
Added the PR preview feature as suggested . Tested it on the following [PR](https://github.com/tcet-opensource/tcet-linux-website/pulls). Let me know if there are any changes.

**Comment by VedantPol** [comment]
Closing as issue has been resolved
